### ISSUE TITLE
A quick question about how to access files other than .py (like csv files)

### ISSUE THREAD

**Issue by HelloWorldLTY** [openproblems-bio/task-dge-perturbation-prediction#13]
Hi, I am now reproducing the exact results from the user who proposed lb2. They have provided four csv files and we only need to aggregrate them. I tried different approaches to read these files but failed. My current yaml file looks like:
<img width="371" alt="image" src="https://github.com/openproblems-bio/task-dge-perturbation-prediction/assets/43333475/c5fa5f03-89ab-49c6-acd3-b3356b8ed9d2">

And my files look like:
<img width="326" alt="image" src="https://github.com/openproblems-bio/task-dge-perturbation-prediction/assets/43333475/3bdeb823-9d0f-48bf-9ba1-cc31ada0fd84">

It seems that my current codes meet a dead lock or dead loop and it stays in this place for a long time:
<img width="991" alt="image" src="https://github.com/openproblems-bio/task-dge-perturbation-prediction/assets/43333475/a57589ea-5dc4-41fd-bb64-38fac09fb155">

If I choose to set file type as python_script, then it will tell me the csv file was not found.

Thanks for your help.

**Comment by rcannood** [comment]
Also, why are you passing the `--de_test` to your component?

Can you point me to the branch where your code is located to get a better idea of what's going wrong?

**Comment by HelloWorldLTY** [comment]
Sorry to make you all feel confused. I intend to pass the sample_submission.csv file for access to check if I can fully reproduce the results.

My current branch is lb2.
